{% set name = "uvicorn" %}
{% set version = "0.16.0" %}

package:
  name: {{ name }}-standard
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/uvicorn/uvicorn-{{ version }}.tar.gz
  sha256: eacb66afa65e0648fcbce5e746b135d09722231ffffc61883d4fac2b62fbea8d

build:
  number: 1

requirements:
  run:
    - {{ pin_subpackage(name, exact=True) }}
    - websockets >=10.0
    - httptools >=0.2.0,<0.4.0
    - uvloop >=0.14.0,!=0.15.0,!=0.15.1  # [python_impl == "cpython" and not win]
    - colorama >=0.4  # [win]
    - watchgod >=0.6
    - python-dotenv >=0.13
    - PyYAML >=5.1

test:
  requires:
    - pip
  imports:
    - uvicorn
  commands:
    - pip check
    - uvicorn --help

outputs:
  - name: {{ name }}

    build:
      entry_points:
        - uvicorn = uvicorn.main:main
    script: build.sh  # [not win]
    script: bld.bat  # [win]

    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python
        - pip
      run:
        - python
        - asgiref >=3.4.0
        - click >=7.*
        - h11 >=0.8
        - typing-extensions  # [py<38]

    test:
      imports:
        - uvicorn
      commands:
        - pip check
        - uvicorn --help

about:
  home: https://pypi.org/project/uvicorn/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The lightning-fast ASGI server. 🦄
  description: |
    Uvicorn is a lightning-fast ASGI server implementation,
    using [uvloop](https://github.com/MagicStack/uvloop) and
    [httptools](https://github.com/MagicStack/httptools).
  doc_url: https://www.uvicorn.org/
  dev_url: https://github.com/encode/uvicorn

extra:
  recipe-maintainers:
    - carlodri
    - ocefpaf
    - xhochy
